[package]
name = "wasm-test"
version = "0.1.0"
edition = "2018"

[dependencies]
surf = { path = "..", default-features = false, features = ["wasm-client"] }
wasm-bindgen-test = "0.3.24"
async-std = "1.6.4"
serde_json = "1.0.57"

[dependencies.getrandom]
version = "0.2"
features = ["js"]
