[package]
name = "wasm-test"
version = "0.1.0"
edition = "2018"

[dependencies]
surf = { path = "..", default-features = false, features = ["wasm-client"] }
wasm-bindgen-test = "0.3.36"
async-std = "1.12.0"
serde_json = "1.0.96"

